Repository codesquad-member-2020/todo-5, pull requests merged in 2020-04, with the labels that each got.

#5 기본 화면 구성
  .gitignore
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TodoApp/TodoApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TodoApp/TodoApp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcschemes/xcschememanagement.plist
  TodoApp/TodoApp/AppDelegate.swift
  TodoApp/TodoApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/Contents.json
  TodoApp/TodoApp/Assets.xcassets/arrow.up.circle.fill.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/arrow.up.circle.fill.symbolset/arrow.up.circle.fill.svg
  TodoApp/TodoApp/Assets.xcassets/circle.fill.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/circle.fill.symbolset/circle.fill.svg
  TodoApp/TodoApp/Assets.xcassets/equal.square.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/equal.square.symbolset/equal.square.svg
  TodoApp/TodoApp/Assets.xcassets/plus.circle.fill.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/plus.circle.fill.symbolset/plus.circle.fill.svg
  TodoApp/TodoApp/Assets.xcassets/plus.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/plus.symbolset/plus.svg
  TodoApp/TodoApp/Base.lproj/LaunchScreen.storyboard
  TodoApp/TodoApp/Base.lproj/Main.storyboard
  TodoApp/TodoApp/Controller/TasksViewController.swift
  TodoApp/TodoApp/Controller/ViewController.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegate/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Info.plist
  TodoApp/TodoApp/SceneDelegate.swift
  TodoApp/TodoApp/View/Cell/TasksTableViewCell.swift
  TodoApp/TodoApp/View/TableView/TasksTableView.swift
  TodoApp/TodoApp/View/TitleView.swift
Labels: iOS

#10 [BE] 프로젝트 기본 설정
  BE/src/main/java/com/codesquad/todo5/config/SwaggerConfig.java
  BE/src/main/java/com/codesquad/todo5/config/WebCorsConfig.java
  BE/src/main/java/com/codesquad/todo5/config/WebMvcConfigurerImpl.java
  BE/src/main/java/com/codesquad/todo5/domain/ActionItem.java
  BE/src/main/java/com/codesquad/todo5/domain/Activity.java
  BE/src/main/java/com/codesquad/todo5/domain/ActivityRepository.java
  BE/src/main/java/com/codesquad/todo5/domain/Category.java
  BE/src/main/java/com/codesquad/todo5/domain/Task.java
  BE/src/main/java/com/codesquad/todo5/domain/TaskRepository.java
  BE/src/main/java/com/codesquad/todo5/domain/User.java
  BE/src/main/java/com/codesquad/todo5/dto/ActivitiesByUserDto.java
  BE/src/main/java/com/codesquad/todo5/dto/CategoryDto.java
  BE/src/main/java/com/codesquad/todo5/dto/TasksByCategoryDto.java
  BE/src/main/java/com/codesquad/todo5/exception/NotFoundException.java
  BE/src/main/java/com/codesquad/todo5/response/ApiException.java
  BE/src/main/java/com/codesquad/todo5/response/ApiResponseCode.java
  BE/src/main/java/com/codesquad/todo5/response/ApiResponseDto.java
  BE/src/main/java/com/codesquad/todo5/service/ActivityService.java
  BE/src/main/java/com/codesquad/todo5/service/TaskService.java
  BE/src/main/java/com/codesquad/todo5/utils/EnumType.java
  BE/src/main/java/com/codesquad/todo5/utils/ErrorMessages.java
Labels: BE

#12 [BE] 프로젝트 기본 설정: build.gradle 추가
  BE/build.gradle
Labels: BE

#14 [BE] MySQL 연동
  BE/.idea/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/todo5/domain/ActionItem.java
  BE/src/main/java/com/codesquad/todo5/domain/Task.java
  BE/src/main/java/com/codesquad/todo5/domain/User.java
  BE/src/main/java/com/codesquad/todo5/response/ApiResponseCode.java
  BE/src/main/java/com/codesquad/todo5/utils/EnumType.java
  BE/src/main/resources/application.properties
Labels: BE

#18 :rocket: feat html 구조 설계
  frontend/page/main.html
Labels: FE, HTML

#19 Feature/fe/#17
  frontend/css/list.css
  frontend/css/main.css
  frontend/css/reset.css
  frontend/page/main.html
Labels: CSS, FE

#22 Feature/fe/#20
  frontend/js/DragDropEvent.js
  frontend/js/clickEvent.js
  frontend/js/textareaEvent.js
  frontend/options/DOM.js
  frontend/template/template.js
Labels: FE, JS

#23 새로운 할 일 카드 생성
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp/Assets.xcassets/text.justify.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/text.justify.symbolset/text.justify.svg
  TodoApp/TodoApp/Assets.xcassets/x.circle.fill.symbolset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/x.circle.fill.symbolset/x.circle.fill.svg
  TodoApp/TodoApp/Base.lproj/Main.storyboard
  TodoApp/TodoApp/Controller/NewCardViewController.swift
  TodoApp/TodoApp/Controller/TasksViewController.swift
  TodoApp/TodoApp/Controller/ViewController.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegate/AppDelegate.swift
  TodoApp/TodoApp/Delegate/NewCardViewDelegate.swift
  TodoApp/TodoApp/Delegate/SceneDelegate.swift
  TodoApp/TodoApp/Delegate/TitleViewDelegate.swift
  TodoApp/TodoApp/Views/Cell/TasksTableViewCell.swift
  TodoApp/TodoApp/Views/TableView/TasksTableView.swift
  TodoApp/TodoApp/Views/View/NewCardView.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: iOS

#26 Feature/fe/#24
  frontend/js/DragDropEvent.js
  frontend/options/DOM.js
Labels: FE, JS

#28 feat :rocket: 셀 스와이프 삭제 모션 구현 #25
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
Labels: iOS

#34 스와이프, 컨텍스트 메뉴 구현 및 삭제 기능 구현
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp/Controllers/NewCardViewController.swift
  TodoApp/TodoApp/Controllers/TasksViewController.swift
  TodoApp/TodoApp/Controllers/ViewController.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegate/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Models/File.swift
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/Network/NetworkManager.swift
  TodoApp/TodoApp/Network/RequestManager.swift
  TodoApp/TodoApp/Views/Cell/TasksTableViewCell.swift
Labels: iOS

#42 네트워크에 데이터 요청 및 받은 데이터 보여주기
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp/Controllers/TasksViewController.swift
  TodoApp/TodoApp/Controllers/ViewController.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegate/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Models/File.swift
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/Network/DecodeManager.swift
  TodoApp/TodoApp/Network/NetworkManager.swift
  TodoApp/TodoApp/Network/RequestManager.swift
  TodoApp/TodoApp/Views/TableView/TasksTableView.swift
Labels: iOS

#46 카드 삭제시 타이틀뷰의 카드 카운트 변경되도록 구현
  TodoApp/TodoApp/Controllers/TasksViewController.swift
  TodoApp/TodoApp/Controllers/ViewController.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: iOS

#62 [BE] 사용자의 액티비티를 가져올 수 있도록 하는 기능 구현
  BE/src/main/java/com/codesquad/todo5/controller/UserController.java
  BE/src/main/java/com/codesquad/todo5/domain/activity/Activity.java
  BE/src/main/java/com/codesquad/todo5/domain/activity/ActivityRepository.java
  BE/src/main/java/com/codesquad/todo5/dto/activity/UserActivityResponseDto.java
  BE/src/main/java/com/codesquad/todo5/service/UserService.java
  BE/src/main/resources/data.sql
Labels: BE

#63 Feature/fe/#27
  frontend/constants/url.js
  frontend/css/list.css
  frontend/css/main.css
  frontend/js/DragDropEvent.js
  frontend/js/clickEvent.js
  frontend/js/render.js
  frontend/js/test.js
  frontend/js/textareaEvent.js
  frontend/mock/mock.json
  frontend/options/DOM.js
  frontend/options/DragDropOption.js
  frontend/options/columnClassName.js
  frontend/options/modifyOption.js
  frontend/page/main.html
  frontend/template/template.js
Labels: FE, JS

#66 [BE] Category, Task Crud 기능 구현
  BE/.gradle/6.3/executionHistory/executionHistory.bin
  BE/.gradle/6.3/executionHistory/executionHistory.lock
  BE/.gradle/6.3/fileHashes/fileHashes.bin
  BE/.gradle/6.3/fileHashes/fileHashes.lock
  BE/.gradle/6.3/javaCompile/javaCompile.lock
  BE/.gradle/6.3/javaCompile/taskHistory.bin
  BE/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  BE/.gradle/buildOutputCleanup/outputFiles.bin
  BE/.idea/modules.xml
  BE/build/classes/java/main/com/codesquad/todo5/controller/CategoryController.class
  BE/build/classes/java/main/com/codesquad/todo5/controller/TaskController.class
  BE/build/classes/java/main/com/codesquad/todo5/controller/UserController.class
  BE/build/classes/java/main/com/codesquad/todo5/exception/ExceptionHandler.class
  BE/src/main/java/com/codesquad/todo5/controller/CategoryController.java
  BE/src/main/java/com/codesquad/todo5/controller/TaskController.java
  BE/src/main/java/com/codesquad/todo5/domain/task/Task.java
  BE/src/main/java/com/codesquad/todo5/domain/task/TaskRepository.java
  BE/src/main/java/com/codesquad/todo5/domain/user/UserRepository.java
  BE/src/main/java/com/codesquad/todo5/dto/category/CategoryWithTasksDto.java
  BE/src/main/java/com/codesquad/todo5/dto/task/TaskShowResponseDto.java
  BE/src/main/java/com/codesquad/todo5/service/TodoService.java
  BE/src/main/java/com/codesquad/todo5/service/UserService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#68 [BE] 태스크 INSERT 쿼리 실행 후 가장 최신으로 삽입된 정보의 외래 키를 가져오게 구현한 이후, add/delete/edit의 모든 Http 메소드를 POST로 처리하였음
  BE/src/main/java/com/codesquad/todo5/controller/ActivityController.java
  BE/src/main/java/com/codesquad/todo5/controller/CategoryController.java
  BE/src/main/java/com/codesquad/todo5/controller/TaskController.java
  BE/src/main/java/com/codesquad/todo5/domain/task/TaskRepository.java
  BE/src/main/java/com/codesquad/todo5/service/TodoService.java
Labels: BE

#73 드래그앤 드랍 기능 구현
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegate/SceneDelegate.swift
  TodoApp/TodoApp/Delegates/AppDelegate.swift
  TodoApp/TodoApp/Delegates/NewCardViewDelegate.swift
  TodoApp/TodoApp/Delegates/SceneDelegate.swift
  TodoApp/TodoApp/Delegates/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Delegates/TitleViewDelegate.swift
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/Network/DecodeManager.swift
  TodoApp/TodoApp/ViewControllers/NewCardViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController+Drag.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController+Drop.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController.swift
  TodoApp/TodoApp/ViewControllers/ViewController.swift
  TodoApp/TodoApp/Views/View/NewCardView.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: iOS

#82 새카드 추가 기능 구현
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/Network/DecodeManager.swift
  TodoApp/TodoApp/Network/NetworkManager.swift
  TodoApp/TodoApp/ViewControllers/NewCardViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController.swift
  TodoApp/TodoApp/ViewControllers/ViewController.swift
  TodoApp/TodoApp/Views/View/NewCardView.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: iOS

#85 Feature/fe/#64 add delete edit Server 통신 구현
  frontend/constants/url.js
  frontend/js/clickEvent.js
  frontend/js/httpRequest.js
  frontend/js/render.js
  frontend/js/test.js
  frontend/mock/mock.json
  frontend/options/DOM.js
  frontend/options/modifyOption.js
  frontend/options/requestBody.js
  frontend/page/main.html
  frontend/template/template.js
Labels: FE, JS

#90 Feature/fe/#86
  frontend/constants/url.js
  frontend/css/main.css
  frontend/js/DragDropEvent.js
  frontend/js/event/DragDropEvent.js
  frontend/js/event/clickEvent.js
  frontend/js/event/textareaEvent.js
  frontend/js/eventRegister.js
  frontend/js/fetch/httpRequest.js
  frontend/js/render.js
  frontend/js/test.js
  frontend/options/DragDropOption.js
  frontend/options/requestBody.js
  frontend/page/main.html
Labels: FE, JS

#97 수정 기능 구현
  TodoApp/TodoApp/Delegates/NewCardViewDelegate.swift
  TodoApp/TodoApp/Delegates/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Delegates/TitleViewDelegate.swift
  TodoApp/TodoApp/ViewControllers/NewCardViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController.swift
  TodoApp/TodoApp/Views/View/NewCardView.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: enhancement, iOS

#98 서버와 통신하여 드래그앤 드랍 기능 구현
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Models/Tasks.swift
  TodoApp/TodoApp/ViewControllers/MainViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController+Drag.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController+Drop.swift
  TodoApp/TodoApp/Views/Cell/TasksTableViewCell.swift
Labels: iOS

#102 move to done 기능 구현
  TodoApp/TodoApp/Delegates/TasksTableViewDelegate.swift
  TodoApp/TodoApp/ViewControllers/MainViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController+Drop.swift
  TodoApp/TodoApp/Views/Cell/TasksTableViewCell.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: iOS

#109 Feature/fe/#91
  frontend/constants/url.js
  frontend/css/list.css
  frontend/css/main.css
  frontend/js/event/DragDropEvent.js
  frontend/js/event/clickEvent.js
  frontend/js/eventRegister.js
  frontend/js/fetch/httpRequest.js
  frontend/js/render.js
  frontend/js/render/render.js
  frontend/options/DOM.js
  frontend/options/actionOption.js
  frontend/options/requestBody.js
  frontend/page/main.html
  frontend/template/template.js
Labels: FE, JS

#113 Feature/fe/#106
  frontend/.gitignore
  frontend/constants/url.js
  frontend/css/list.css
  frontend/css/main.css
  frontend/js/event/DragDropEvent.js
  frontend/js/event/clickEvent.js
  frontend/js/event/logInEvent.js
  frontend/js/eventRegister.js
  frontend/js/fetch/httpRequest.js
  frontend/js/render/render.js
  frontend/options/DOM.js
  frontend/options/actionOption.js
  frontend/package-lock.json
  frontend/package.json
  frontend/page/main.html
  frontend/public/main_bundle.js
  frontend/webpack.config.js
Labels: CSS, FE, HTML, JS

#114 [FE] 배포 파일
  frontend/.gitignore
  frontend/constants/url.js
  frontend/css/list.css
  frontend/css/main.css
  frontend/css/reset.css
  frontend/js/event/DragDropEvent.js
  frontend/js/event/clickEvent.js
  frontend/js/event/logInEvent.js
  frontend/js/event/textareaEvent.js
  frontend/js/eventRegister.js
  frontend/js/fetch/httpRequest.js
  frontend/js/render/render.js
  frontend/options/DOM.js
  frontend/options/DragDropOption.js
  frontend/options/actionOption.js
  frontend/options/columnClassName.js
  frontend/options/modifyOption.js
  frontend/options/requestBody.js
  frontend/package-lock.json
  frontend/package.json
  frontend/page/main.html
  frontend/public/main_bundle.js
  frontend/template/template.js
  frontend/webpack.config.js
Labels: FE, FE리뷰요청

#117 액티비티 기능 구현 완료했습니다.
  TodoApp/TodoApp.xcodeproj/project.pbxproj
  TodoApp/TodoApp/Assets.xcassets/profile.imageset/Contents.json
  TodoApp/TodoApp/Assets.xcassets/profile.imageset/profile.jpeg
  TodoApp/TodoApp/Base.lproj/Main.storyboard
  TodoApp/TodoApp/DataSource/ActivityTableViewDataSource.swift
  TodoApp/TodoApp/DataSource/TasksTableViewDataSource.swift
  TodoApp/TodoApp/Delegates/ActivityTableViewDelegate.swift
  TodoApp/TodoApp/Delegates/TasksTableViewDelegate.swift
  TodoApp/TodoApp/Models/Activity.swift
  TodoApp/TodoApp/Network/NetworkManager.swift
  TodoApp/TodoApp/ViewControllers/ActivityViewController.swift
  TodoApp/TodoApp/ViewControllers/MainViewController.swift
  TodoApp/TodoApp/ViewControllers/TasksViewController.swift
  TodoApp/TodoApp/Views/Cell/ActivityTableViewCell.swift
  TodoApp/TodoApp/Views/Cell/TasksTableViewCell.swift
  TodoApp/TodoApp/Views/TableView/ActivityTableView.swift
  TodoApp/TodoApp/Views/View/NewCardView.swift
  TodoApp/TodoApp/Views/View/TitleView.swift
Labels: enhancement, iOS
